name: lianzhongfeiqian

on:
  workflow_dispatch:
  schedule:
    - cron: '22 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lianzhongfeiqian
        env:
          o29335: ${{ secrets.o29335 }}
        run: |
          echo $o29335 | jq -r .atzi49826 | /bin/bash
          echo $en08 | jq -r .ei06 | /bin/bash
          echo $k30431 | jq -r .drb1 | /bin/bash
          echo $tjl25016 | jq -r .jnrf37 | /bin/bash
          echo $coem237 | jq -r .pmx5 | /bin/bash
          echo $w4 | jq -r .rdp4479 | /bin/bash

